const canonical = [
  ["default","Normal","5 4"],["pointer","Hover","21 8"],["grab","Mão aberta","24 24"],["grabbing","Arrastando","24 24"],["copy","Copiar","5 4"],["alias","Link","5 4"],["no-drop","Bloqueado","5 4"],["all-scroll","Mover","24 24"],["cell","Célula","24 24"],["col-resize","Coluna","24 24"],["context-menu","Menu de contexto","5 4"],["crosshair","Mira","24 24"],["e-resize","Leste","24 24"],["ew-resize","Leste ↔ oeste","24 24"],["help","Ajuda","24 24"],["n-resize","Norte","24 24"],["ne-resize","Nordeste","24 24"],["nesw-resize","Nordeste ↔ sudoeste","24 24"],["none","Oculto","0 0"],["ns-resize","Norte ↔ sul","24 24"],["nw-resize","Noroeste","24 24"],["nwse-resize","Noroeste ↔ sudeste","24 24"],["progress","Progresso","5 4"],["row-resize","Linha","24 24"],["s-resize","Sul","24 24"],["se-resize","Sudeste","24 24"],["sw-resize","Sudoeste","24 24"],["text","Texto","24 24"],["wait","Aguarde","24 24"],["w-resize","Oeste","24 24"],["zoom-in","Zoom +","21 21"],["zoom-out","Zoom −","21 21"]
];
const aliases = [["watch","wait"],["left_ptr_watch","progress"],["auto","default"],["left_ptr","default"],["arrow","default"],["top_left_arrow","default"],["hand","pointer"],["hand1","pointer"],["hand2","pointer"],["openhand","grab"],["closedhand","grabbing"],["dnd-move","grabbing"],["fleur","grabbing"],["dnd-copy","copy"],["plus","copy"],["dnd-link","alias"],["link","alias"],["not-allowed","no-drop"],["crossed_circle","no-drop"],["move","all-scroll"]];
const srcFor = (name) => ({default:"arrow",pointer:"hover"}[name] ?? name);
const all = canonical.map(function(item){ return {name:item[0],label:item[1],hot:item[2],source:srcFor(item[0])}; }).concat(aliases.map(function(item){ const target=canonical.find(function(row){return row[0]===item[1];}); return {name:item[0],label:"Alias de "+item[1],hot:target ? target[2] : "24 24",source:srcFor(item[1]),alias:true}; }));
const catalog = document.querySelector("#catalog"), count = document.querySelector("#count");
all.forEach(function(item){ const card=document.createElement("article"); card.className="cursor-card"+(item.alias ? " is-alias" : ""); card.dataset.name=item.name; card.style.setProperty("--cursor",'url("src/'+item.source+'.svg") '+item.hot+", auto"); card.innerHTML="<code>"+item.name+"</code><small>"+item.label+(item.alias ? " · alias" : "")+"</small>"; catalog.append(card); });
const filter=document.querySelector("#filter");
function applyFilter(){ const query=filter.value.trim().toLowerCase(); let visible=0; Array.from(catalog.children).forEach(function(card){ const show=!query || card.dataset.name.includes(query) || card.textContent.toLowerCase().includes(query); card.hidden=!show; if(show) visible++; }); count.value="("+visible+"/"+all.length+")"; }
filter.addEventListener("input",applyFilter); applyFilter();
const drag=document.querySelector("#drag-source"), drop=document.querySelector("#drop-zone");
drag.addEventListener("dragstart",function(event){ drag.classList.add("dragging"); event.dataTransfer.setData("text/plain","aroli-cursor"); }); drag.addEventListener("dragend",function(){ drag.classList.remove("dragging"); }); drop.addEventListener("dragover",function(event){ event.preventDefault(); drop.classList.add("over"); }); drop.addEventListener("dragleave",function(){ drop.classList.remove("over"); }); drop.addEventListener("drop",function(event){ event.preventDefault(); drop.classList.remove("over"); drop.textContent="DROP / GRAB"; });
