// Shared anatomical landmarks, with articulated contours for each pose.
// Edit this source, never the generated SVGs.
const root = new URL("../src/", import.meta.url);
const anatomy = {
  // Continuous outer palm, plain wrist, rounded thenar/thumb transition.
  // Every upper contour ends at the same little-finger base (39, 25).
  lower: "C39.8 30.5 37 35 33 38V40.5Q33 42 31.5 42H23.5Q22 42 22 40.5V38C18.8 35.8 16 32.5 13.5 29C11.7 26.5 10.8 24 12.5 23C14.3 21.9 16 23.6 17 26",
  outline: 2.5,
};
const poses = {
  // Index extends from the radial side of the palm; the remaining knuckles fold.
  hover: "M17 26C18.5 24.2 19.5 21.3 18.9 17.5L17.7 11C16.9 6.5 22.8 5.5 23.6 10C24.1 12.9 24.2 16.1 25 19C25.1 15.4 29.6 15.1 30 19.3C30.8 16.8 34.8 17.3 35 20.9C36.2 18.9 39.2 19.6 39.4 22.3C39.5 23.3 38.85 24 39 25",
  // Arched MCP line; tapered, slightly splayed fingers and shallow rounded webs.
  grab: "M17 26C17.8 23.2 16.4 18.5 15.3 14.3C14.2 10.3 19.3 8.7 20.9 12.3L23 19C23.5 19.8 24 19.5 24 18L23.5 9C23.3 5 28.8 4.7 29 8.7L29.5 18C29.5 19.5 30.5 19.5 31 18L32.3 12.3C33 8.7 37.8 9.5 37.2 13.3L35.6 21.1C35.5 22 36.3 22.2 37 21.1L39.1 18.4C40.5 15.2 45.2 17.1 43.7 20.5C43 23.4 38.8 23.4 39 25",
  // Flexed fingers form a compact rounded mass; not shortened open fingers.
  grabbing: "M17 26C16.7 24.8 16.1 23.5 15.9 22C15.1 17.8 19.3 15.4 22 18.3C22.2 14.3 27.2 13.7 29 17.2C30.4 14.6 35.1 16.1 35 19.2C37.3 17.2 40.2 19.6 40 22.2L39 25",
};
for (const [name, upper] of Object.entries(poses)) {
  const d = upper + anatomy.lower + "Z";
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <!-- Generated by scripts/generate-hands.ts; silhouette carries the anatomy. -->
  <path d="${d}" fill="#C5C7C5" stroke="#050505" stroke-linejoin="round" stroke-linecap="round" stroke-width="${anatomy.outline}"/>
</svg>\n`;
  const file = new URL(`${name}.svg`, root);
  if (process.argv.includes("--check")) {
    if (await Bun.file(file).text() !== svg) throw new Error(`${name}: generated SVG is stale; run make hands`);
  } else {
    await Bun.write(file, svg);
  }
}
// A separate silhouette plate removes color, labels inside the shapes and details.
{
  const silhouettes = Object.entries(poses).map(([name, upper], index) =>
    `<g transform="translate(${32 + index * 192} 40)"><path d="${upper + anatomy.lower}Z" transform="scale(3)" fill="#050505"/><text x="72" y="158" text-anchor="middle" font-family="sans-serif" font-size="16">${name}</text></g>`).join("");
  const file = new URL("../silhouettes.svg", root);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="256" viewBox="0 0 640 256"><rect width="640" height="256" fill="#eee"/>${silhouettes}</svg>\n`;
  if (process.argv.includes("--check")) {
    if (await Bun.file(file).text() !== svg) throw new Error("Silhouette plate is stale; run make hands");
  } else {
    await Bun.write(file, svg);
  }
}
